### ISSUE TITLE
tag 0.2.0 编译出来的是 GUI 界面，无法启动相应的 airisp 功能

### ISSUE THREAD

**Issue by taotieren** [Air-duino/AirISP-next#7]
tag 0.2.0 编译出来的是 GUI 界面，无法启动相应的 airisp 功能

**Comment by chenxuuu** [comment]
加上命令行参数就是命令行了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月23日(周二) 下午4:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Air-duino/AirISP-next] tag 0.2.0 编译出来的是 GUI 界面，无法启动相应的 airisp 功能 (Issue #7)




 
tag 0.2.0 编译出来的是 GUI 界面，无法启动相应的 airisp 功能

**Comment by taotieren** [comment]
GUI 还没用起来吗？

```bash
❯ airisp-next --help
AirISP 是一个 Flash 烧录工具

Usage: airisp-next [OPTIONS] <COMMAND>

Commands:
  write_flash  烧录 Flash
  chip_id      获取芯片ID
  help         Print this message or the help of the given subcommand(s)

Options:
  -p, --port <port>
          串口号 [default: auto]
  -c, --chip <chip>
          芯片型号 [default: auto]
  -b, --baud <baud>
          波特率 [default: 0]
  -t, --trace[=<trace>]
          是否打印调试信息 [default: false] [possible values: true, false]
      --connect-attempts <connect_attempts>
          最大重试次数，等于0表示无限次 [default: 10]
      --before <before>
          烧录前执行的操作 [default: default_reset] [possible values: direct_connect, default_reset]
      --after <after>
          烧录后执行的操作 [default: hard_reset] [possible values: hard_reset]
      --peripheral <peripheral>
          烧录使用的外设 [default: Uart]
      --language <language>
          zh-CN.language_help [default: auto] [possible values: auto, en, zh-CN, ja]
  -h, --help
          Print help
  -V, --version
          Print version

```

**Comment by chenxuuu** [comment]
gui功能都没写



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月24日(周三) 晚上10:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Air-duino/AirISP-next] tag 0.2.0 编译出来的是 GUI 界面，无法启动相应的 airisp 功能 (Issue #7)




 
GUI 还没用起来吗？
 ❯ airisp-next --help AirISP 是一个 Flash 烧录工具 Usage: airisp-next [OPTIONS] <COMMAND&gt; Commands:   write_flash  烧录 Flash   chip_id      获取芯片ID   help         Print this message or the help of the given subcommand(s) Options:   -p, --port <port&gt;           串口号 [default: auto]   -c, --chip <chip&gt;           芯片型号 [default: auto]   -b, --baud <baud&gt;           波特率 [default: 0]   -t, --trace[=<trace&gt;]           是否打印调试信息 [default: false] [possible values: true, false]       --connect-attempts <connect_attempts&gt;           最大重试次数，等于0表示无限次 [default: 10]       --before <before&gt;           烧录前执行的操作 [default: default_reset] [possible values: direct_connect, default_reset]       --after <after&gt;           烧录后执行的操作 [default: hard_reset] [possible values: hard_reset]       --peripheral <peripheral&gt;           烧录使用的外设 [default: Uart]       --language <language&gt;           zh-CN.language_help [default: auto] [possible values: auto, en, zh-CN, ja]   -h, --help           Print help   -V, --version           Print version
